### PR TITLE
Add support for Gnome 45

### PR DESCRIPTION
**Pull request by cabemo**
This solves #32

### CODE REVIEW

**Comment by cabemo** [comment]
Also updated coingecko's list

**Comment by alipirpiran** [comment]
Thanks
I think it is better to remove shell-version below 45 from metadata.json/shell-version

**Comment by mrcbq** [comment]
Hey @cabemo and @alipirpiran, A lot of Thanks!

**Comment by alipirpiran** [comment]
@cabemo removing the `createUUID` function in [commit](https://github.com/alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell/commit/9c428aec461eb6e2472bef746c1fa834c5694d37#diff-13dc23064e793dea7dd9e6b13202f6e7ba564c275582c836dfef0b3e1f96eb9f), this function was used in `addCoinMenuItem.js:_addCoin()` caused a bug when adding new coins. I added the function in new version.

**Pull request merged**
